### ISSUE TITLE
Add retry support and durable log shipping in `EventCollectorSink`

### ISSUE THREAD

**Issue by caioproiete** [serilog/serilog-sinks-splunk#116] opened 2019-09-06 01:37 UTC
... similar to [Seq's durable log shipping](https://docs.datalust.co/docs/using-serilog#section-asynchronous-batching-and-durable-log-shipping), to help prevent messages from being discarded when the Splunk Event Collector cannot receive messages.

Related StackOverflow question: [Log messages discarded when logging to Splunk using Serilog
](https://stackoverflow.com/questions/57801885/log-messages-discarded-when-logging-to-splunk-using-serilog/)

**Comment by merbla** [comment] 2019-09-06 01:40
I think this is related to #82

**Comment by caioproiete** [comment] 2019-09-06 01:50
@merbla: Oh yes, sorry, they're the same... Feel free to close as duplicate.

**Comment by merbla** [comment] 2019-12-26 21:59
Dupe of https://github.com/serilog/serilog-sinks-splunk/issues/82

**Closed by merbla** 2019-12-26 21:59 UTC
