### ISSUE TITLE
upgrade to 3.5.0 in aspnet core web api project causes exception on configuraiton

### ISSUE THREAD

**Issue by fspataro** [serilog/serilog-sinks-splunk#137] opened 2020-10-12 19:22 UTC
Hi, 
I clicked the simple 'package manager' update inside visual studio to upgrade from 3.4.0 to 3.5.0 and now the configuration throws the following error:

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=queue limit must be positive (Parameter 'queueLimit')
  Source=Serilog.Sinks.PeriodicBatching
  StackTrace:
   at Serilog.Sinks.PeriodicBatching.BoundedConcurrentQueue`1..ctor(Int32 queueLimit)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink..ctor(Int32 batchSizeLimit, TimeSpan period, Int32 queueLimit)
   at Serilog.Sinks.Splunk.EventCollectorSink..ctor(String splunkHost, String eventCollectorToken, String uriPath, Int32 batchIntervalInSeconds, Int32 batchSizeLimit, Nullable`1 queueLimit, ITextFormatter jsonFormatter, HttpMessageHandler messageHandler)
   at Serilog.Sinks.Splunk.EventCollectorSink..ctor(String splunkHost, String eventCollectorToken, String uriPath, String source, String sourceType, String host, String index, Int32 batchIntervalInSeconds, Int32 batchSizeLimit, Nullable`1 queueLimit, IFormatProvider formatProvider, Boolean renderTemplate, HttpMessageHandler messageHandler)
   at Serilog.SplunkLoggingConfigurationExtensions.EventCollector(LoggerSinkConfiguration configuration, String splunkHost, String eventCollectorToken, String uriPath, String source, String sourceType, String host, String index, LogEventLevel restrictedToMinimumLevel, IFormatProvider formatProvider, Boolean renderTemplate, Int32 batchIntervalInSeconds, Int32 batchSizeLimit, Nullable`1 queueLimit, HttpMessageHandler messageHandler, LoggingLevelSwitch levelSwitch)

Runs again fine if I back it back down to 3.4.0.  Is there a specific step need to maintain the upgrade?  

My code:
(pretty stock Startup.cs, inside Startup.Startup(IConfiguration configuration) {}

Log.Logger = new LoggerConfiguration()
				.WriteTo.Console()
				.WriteTo.EventCollector(
					Configuration.GetValue<string>("Splunk:splunkHost")
					, Configuration.GetValue<string>("Splunk:eventCollectorToken")
					, sourceType: "docgen")
				.CreateLogger();

Thanks

**Comment by garster** [comment] 2020-10-14 15:16
I have an ASP.NET Core MVC app that also has issues with 3.5.

When I run the app in Visual Studio the Output window shows

```
Exception thrown: 'System.ArgumentOutOfRangeException' in Serilog.Sinks.PeriodicBatching.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
```
Then the app exits and I cannot debug. Reverting back to 3.4 solves the problem.

**Comment by JuanjoFuchs** [comment] 2020-10-14 20:37
Hello @fspataro, yes this is a bug only present on 3.5.0 and PR #138 is open to address it.
In the meantime, if you need to use 3.5.0, you need to specify a "queueLimit".

From your code, it would look like:
```csharp
.WriteTo.EventCollector(
    Configuration.GetValue("Splunk:splunkHost")
    , Configuration.GetValue("Splunk:eventCollectorToken")
    , sourceType: "docgen"
    , queueLimit: 100000) 
```

**Comment by fspataro** [comment] 2020-10-14 20:40
@JuanjoFuchs thanks!

**Comment by JuanjoFuchs** [comment] 2020-10-15 20:48
@fspataro the issue is no longer present on v3.6.0

**Comment by merbla** [comment] 2021-11-07 00:59
Closing as a part of larger Serilog contrib reorg

Checkout serilog/serilog#1627

**Closed by merbla** 2021-11-07 00:59 UTC
